org: jaysp

service: bannerService
custom:
  ServiceName: ${self:service}
  Stage: ${opt:stage, 'dev'}  

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - "*" 
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
  stage: ${opt:stage, 'dev'} 
  environment:
    BUCKET_NAME: banner-images-jaysp-jy952466-new
    DYNAMO_TABLE: Banners
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject 
      Resource: arn:aws:s3:::banner-images-jaysp-jy952466-new/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamoDb:Scan 
      Resource: arn:aws:dynamodb:us-east-1:601148044385:table/Banners
  

resources:
   Resources:
      BannerImagesBucket:
         Type: AWS::S3::Bucket 
         Properties:
           BucketName: banner-images-jaysp-jy952466-new 
           CorsConfiguration:
            CorsRules:
              - AllowedOrigins:
                  - "*"  
                AllowedMethods:
                  - PUT  
                AllowedHeaders:  
                  - "*"
           NotificationConfiguration:  
              LambdaConfigurations:
                - Event: s3:ObjectCreated:Put
                  Function:
                    Fn::GetAtt:
                      - ConfirmUploadLambdaFunction
                      - Arn
           PublicAccessBlockConfiguration:  # DISABLE BLOCK PUBLIC ACCESS
            BlockPublicAcls: false
            IgnorePublicAcls: false
            BlockPublicPolicy: false
            RestrictPublicBuckets: false
      BannerImagesBucketPolicy:  # ALLOW PUBLIC READ ACCESS
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket: banner-images-jaysp-jy952466-new
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal: "*"
                Action: "s3:GetObject"
                Resource: "arn:aws:s3:::banner-images-jaysp-jy952466-new/*"
      #DynamoDB Table Configuration
      BannersTable:
        Type: AWS::DynamoDB::Table 
        Properties:
          TableName: Banners
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: fileName
              AttributeType: S
          KeySchema:
            - AttributeName: fileName
              KeyType: HASH   
      S3ToLambdaPermission:
        Type: AWS::Lambda::Permission
        Properties:
          FunctionName:
            Fn::GetAtt:
              - ConfirmUploadLambdaFunction
              - Arn
          Action: lambda:InvokeFunction
          Principal: s3.amazonaws.com
          SourceArn: arn:aws:s3:::banner-images-jaysp-jy952466-new



functions:
  getUploadUrl:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  getAllBanners:
    handler: handlers/getAllBanners.getAllBanners
    events:
      - httpApi:
          path: /banners
          method: get

  confirmUpload:
    handler: handlers/confirmUpload.confirmUpload
 