org: jaysp
service: authService

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - "*" 
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}
    REGION: us-east-1
  iamRoleStatements:
    - Effect: Allow 
      Action: 
        - dynamodb:PutItem 
      Resource: 
        - arn:aws:dynamodb:us-east-1:601148044385:table/Users


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table #Dynamodb table resource
      Properties:
        TableName: Users 
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions:
          - AttributeName: userId 
            AttributeType: S 
        KeySchema:
          - AttributeName: userId 
            KeyType: HASH 


functions:
  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /sign-up
          method: post
       

  confirmSignUp:
    handler: handlers/confirmSignUp.confirmSignUp
    events:
      - httpApi:
          path: /confirm-sign-up
          method: post   
      
  
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /sign-in
          method: post  
      

  signOut:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /sign-out
          method: post  
   

